server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://{{LOKI_IP}}:3100/loki/api/v1/push

scrape_configs:
- job_name: logpush
  static_configs:
  - targets:
      - {{HOSTIP}}
    labels:
      name: system
      job: syslog
      host: {{HOSTNAME}}
      __path__: /var/log/message
  - targets:
      - {{HOSTIP}}
    labels:
      name: DF正式环境
      job: srvlog
      host: {{HOSTNAME}}
      __path__: /data/logs/*/*.log
